### ISSUE TITLE
Bug on blogs

### ISSUE THREAD

**Issue by MichaelEIC** [CRJI/theblacksea.eu#109]
When I open some of the blog pages to edit, it comes with a bug,

such as the one on 'Ukrainian women are tough - they can stop a horse'

https://wagtail.theblacksea.eu/admin/pages/1191/edit/

![screen shot 2018-10-02 at 17 10 27](https://user-images.githubusercontent.com/30523098/46354031-42886900-c666-11e8-8085-a8e8d7bdc170.png)

**Comment by mgax** [comment]
Check how many blog posts have this problem, then we can decide how to fix it.

**Comment by cpshaw99** [comment]
Is this done? Shall we close the issue?

**Comment by germakoci** [comment]
github protocol says that the person who reported the problem should check and then close the issue so @MichaelEIC back to you

**Comment by cpshaw99** [comment]
Hey @MichaelEIC   The blog pages you re-added don't have the correct dates; they are dated the day you fixed them. Without the correct ones, they'll be out of order forever.
