### ISSUE TITLE
Photo size options

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#113]
There should be three image sizes:
* "embed" (as wide as the text block)
* "wide" (somewhere in between)
* "full" (as wide as the page)

We also need a way to embed small images, e.g. the thumbs-up image in [here](https://wagtail.theblacksea.eu/stories/how-realistic-is-a-union-between-romania-and-moldova/) and perhaps text wrapped around an image.

**Comment by mgax** [comment]
On the current articles, in the streamfield, only "embedded image" is being used, we can safely remove "half_image", "full_image" and "aligned_image" and replace them with whatever makes sense.

Needs input from Petruț.

**Comment by cpshaw99** [comment]
Will create a second image size, using 'col 12' dimentions

**Comment by mgax** [comment]
Done, here's a sample: https://dev.theblacksea.eu/stories/image-test/

So I removed most image types, kept only "embedded image" since it's already in use, and created "image" for new content. "image" has two display options: "embedded" (as wide as the text) and "medium" (full 12 columns, which is bigger than the 8 columns of the text). In the future we will have another image size, "full width", which will be as wide as the browser window.
