### ISSUE TITLE
Intro field for homepage

### ISSUE THREAD

**Issue by MichaelEIC** [CRJI/theblacksea.eu#116]
There needs to be a new field for the intros for the homepage, so these are different from the intros to the stories

Now they follow the story intro

![screen shot 2018-10-01 at 10 55 02](https://user-images.githubusercontent.com/30523098/46475496-53fc7d00-c7ee-11e8-8964-df0c4028cc6c.png)

And they need their own description

![screen shot 2018-10-01 at 10 55 30](https://user-images.githubusercontent.com/30523098/46475531-6ecef180-c7ee-11e8-86f8-4ad54ef9b67b.png)

**Comment by mgax** [comment]
Fixed in https://github.com/CRJI/theblacksea.eu/commit/f6831b48fda3042d4a64bdbd862507209e4c0186
