### ISSUE TITLE
Add images to authors who need a profile page

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#118]

**Comment by cpshaw99** [comment]
we need to decide who has a page. please make an argument for a person, or simply add the people you think need it. 

@germakoci 
@MichaelEIC 
@zsentek

**Comment by MichaelEIC** [comment]
I would include the following, it's a mixture of those who were
instrumental at the beginning, those who worked on two stories or more, and
those still working with us:

ELENA LOMORĂ
REPORTER

IOANA CALINESCU
JOURNALIST, COMMUNICATION

SORINA VAZELINA
ILLUSTRATOR

ALECS CANDEA
DESIGNER

CRINA BOROS
JOURNALIST

ANDREI COTRUȚ
ILLUSTRATOR

ZEYNEP SENTEK
JOURNALIST

PETRUT CALINESCU
PHOTOJOURNALIST, BLACK SEA PHOTO EDITOR

ȘTEFAN CÂNDEA
JOURNALIST

VICTOR AVASILOAEI
DEVELOPER

BLAZ ZGAGA
JOURNALIST

MONICA ULMANU
GRAPHICS JOURNALIST

VLAD ODOBESCU
JOURNALIST

ALEX ULMANU
JOURNALIST

VICTOR NIȚU
CODER

MICHAEL BIRD
JOURNALIST

LINA VDOVÎI
JOURNALIST

LUKE DALE-HARRIS
JOURNALIST

CRAIG SHAW
JOURNALIST

COSTIN STUCAN
JOURNALIST

CATALIN PRISACARIU
JOURNALIST
