### ISSUE TITLE
TBS mothership!

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#122]
Access to TBS Motherboard needs reparing

**Comment by nightsh** [comment]
What is that?!

**Comment by cpshaw99** [comment]
Ha!. I meant, mothership. I am on a call at the same time

**Comment by nightsh** [comment]
mothership is retired, we're not using it anymore

**Comment by mgax** [comment]
So where is theblacksea currently hosted?

**Comment by nightsh** [comment]
The old website, OVH, in a VM.
The WIP site, in the office I guess.

Is this an issue about the old site on the new site's tracker? :thinking:

**Comment by cpshaw99** [comment]
here is no email access

**Comment by nightsh** [comment]
Try https://mail.theblacksea.eu/ for webmail, if that's what you mean. SMTP/POP/IMAP access should be fine, as accounts were migrated with the same password.
