### ISSUE TITLE
Mobile Versions

### ISSUE THREAD

**Issue by MichaelEIC** [CRJI/theblacksea.eu#124]
The mobile versions of the three formats, as well as the blogs, need to be visible and readable

* [x] Headline/standfirst not visible here, plus photos are cut off. Text is visible. https://wagtail.theblacksea.eu/stories/football-leaks-kazakh-moguls-pal-donald-trump-teen-models-and-yacht-father-turks/
* [x] Headline/Standfirst visivble, text visible, but social media icons cover part of text https://wagtail.theblacksea.eu/stories/italian-neofascist-leaders-message-to-local-business-invest-in-crimea/
* [x] All text/headlines etc not visible, pushed to edge https://wagtail.theblacksea.eu/stories/the-boyko-report/
* [x] Story folder image is not tall enough so the title gets cut off https://wagtail.theblacksea.eu/stories/malta-files/

**Comment by cpshaw99** [comment]
the pics on mobile don't work, they are cut too short

**Comment by mgax** [comment]
Images on some legacy stories (https://wagtail.theblacksea.eu/stories/the-boyko-report/) don't scale because they're inlined into the HTML. Others look fine (https://wagtail.theblacksea.eu/stories/the-neapolitan-exodus/) which means the template is fixed now.
