### ISSUE TITLE
Photo stories that need manual copy/paste to the new installation

### ISSUE THREAD

**Issue by germakoci** [CRJI/theblacksea.eu#125]
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1135&recType=photo (foto)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1136&recType=multimedia (video)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1149&recType=multimedia (foto + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1150&recType=multimedia (foto + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1160&recType=photo (galerie foto + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1179&recType=photo (foto + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1201&recType=photo (4 galerii + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1222&recType=photo (video + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1235&recType=multimedia (text Ioana + foto)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1232&recType=multimedia (video + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1245&recType=photo (foto + text)
- [x] https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1262&recType=story (text Ioana + foto)
- [x] https://theblacksea.eu/stories/article/en/living-on-the-edge-photostory (foto + text)
- [x] https://theblacksea.eu/stories/article/en/holidays-in-new-cold-war-photostory (foto + text)
- [x] https://theblacksea.eu/stories/article/en/dream-houses (foto + text)
- [x] https://theblacksea.eu/stories/article/en/romania-after-dark (foto + text)
- [x] https://theblacksea.eu/stories/roma-celebration.html (foto + text)

**Comment by mrc-toader** [comment]
- The article with multiple image carousels has a weird behavior, clicking left / right buttons will only change the first slider's pics. (e.g. https://wagtail.theblacksea.eu/stories/danube-delta-under-the-gaze-of-four-photographers/)
- The video embed streamfield (with vimeo link) adds 56.25% padding bottom, which becomes white empty space below (e.g. https://wagtail.theblacksea.eu/stories/return-of-the-boyars/)

**Comment by mgax** [comment]
> The article with multiple image carousels has a weird behavior

Ah yes, the carousels had the same ID. Fixed.

> The video embed streamfield (with vimeo link) adds 56.25% padding bottom

This is weird, not sure where the padding is coming from. I've made a separate issue and we can deal with it after launch. https://github.com/CRJI/theblacksea.eu/issues/159

**Comment by germakoci** [comment]
is this done @mrc-toader ? can we close the issue ?

**Comment by mrc-toader** [comment]
I wanted to recheck them with fresh eyes.
Last issue regarding these, moved to #159, closing.
