### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#127]
Create a component for social media icons based on the homepage icons and use it on the story template (https://wagtail.theblacksea.eu/stories/last-trial-of-gezi/)

**Comment by mgax** [comment]
These pages have social media links now:

* homepage - https://wagtail.theblacksea.eu/
* blacktail stories - https://wagtail.theblacksea.eu/stories/last-trial-of-gezi/

@cpshaw99 does this look as expected? How should they look on other pages?

**Comment by mgax** [comment]
For stories pages, let's create a box on the left side, with social links and related stories.

**Comment by cpshaw99** [comment]
1. On Blacktail, create 'relates stories' container on the left, which holds social media. See related stories issue

2. There is no social media button for the Malta template
