### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#131]
~pwik? google?~

We installed piwik, which is now called matomo, here: https://matomo.theblacksea.eu. We probably have to [inform our users](https://matomo.org/docs/gdpr/#awareness-documentation) that we track them.

**Comment by mgax** [comment]
We can pay for piwik in the cloud (btw, piwik has been rebranded to "matomo"), it's $7.5/month: https://www.innocraft.cloud/#pricing instead of hosting it ourselves.

**Comment by mgax** [comment]
Or we can self-host the docker: https://hub.docker.com/r/bitnami/matomo/ - I'll spend 30 minutes to set it up, and if it's more complicated, we can pay them.

**Comment by mgax** [comment]
Matomo installed at https://matomo.theblacksea.eu/ - ask me or Craig for an account.

**Comment by germakoci** [comment]
@mgax should I ask Bogdan about how to comply with GDPR new rules when using analytics trackers ?

**Comment by mgax** [comment]
@germakoci Matomo has documentation about GDPR: https://matomo.org/docs/gdpr/ - maybe review that first.

**Comment by mgax** [comment]
I'll reopen the issue because we probably have to install one of those annyoing cookie consent bars.

**Comment by germakoci** [comment]
sorry to spoil the party....but otherwise they could impound Mara....

**Comment by mgax** [comment]
![img_9987](https://user-images.githubusercontent.com/27617/47755665-bfc7ed80-dca7-11e8-9441-4210f71124eb.JPG)

**Comment by mgax** [comment]
So we need a privacy policy page. I'm working on a draft here: https://docs.google.com/document/d/1k9eo0YU_ar3Kf09CT_EQ_Uy9N4GhimwyUwrQID1p8mI/edit#

**Comment by mgax** [comment]
Here is the privacy policy: https://wagtail.theblacksea.eu/privacy-policy/
