### ISSUE TITLE
staging TBS server ?

### ISSUE THREAD

**Issue by germakoci** [CRJI/theblacksea.eu#137]
@mgax does it make sense to keep a staging TBS server (say a wagtail.theblacksea.eu) where we can experiment in the future without breaking the main server ?

**Comment by mgax** [comment]
Good idea. We can keep the existing setup for experimentation when we [move to digitalocean](https://github.com/CRJI/theblacksea.eu/issues/73).

**Comment by germakoci** [comment]
:crystal_ball:

**Comment by mgax** [comment]
We have dev.theblacksea.eu now.
