### ISSUE TITLE
Mirror theblacksea.eu

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#138]
Scrape the old website so we have an easy to use snapshot if we want to reference it after we switch to wagtail.

**Comment by germakoci** [comment]
something like this may do the trick: https://expired1.com/wayback-machine-downloader/ ?

**Comment by mgax** [comment]
I've used http://www.httrack.com/, a tool from the '90s that's still being maintained. Here's the result: https://wagtail.theblacksea.eu/mirror/tbs/theblacksea.eu/ (cc @cpshaw99, @MichaelEIC - please have a look and compare with the original).

One difference I've noticed is that images in old stories are not moved to the right. That movement is done by a horrible javascript hack, I don't really blame the scraper for missing it. :)

**Comment by MichaelEIC** [comment]
Hi, it seems ok for the stories, although the graphics on this story
vanished:

https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1196&recType=story
<https://mailtrack.io/trace/link/5582dea25b021159baf410bee013517c8b432b40?url=https%3A%2F%2Ftheblacksea.eu%2Findex.php%3FidT%3D88%26idC%3D88%26idRec%3D1196%26recType%3Dstory&userId=3513194&signature=832c6dbefb176b08>


so did the one on this story:

https://wagtail.theblacksea.eu/mirror/tbs/theblacksea.eu/eurocrimes/index.html
<https://mailtrack.io/trace/link/ee19c48db2d57cda95453efddbde89f696ed711a?url=https%3A%2F%2Fwagtail.theblacksea.eu%2Fmirror%2Ftbs%2Ftheblacksea.eu%2Feurocrimes%2Findex.html&userId=3513194&signature=e6003f1a38232762>

But with the blogs, it seems that after the first 10 or 20 the others can't
load

**Comment by mgax** [comment]
I've saved as much as was practical to https://wagtail.theblacksea.eu/_old/ (will be https://theblacksea.eu/_old/ once we flip the switch).
