### ISSUE TITLE
Embedded image quality

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#139]
The images being loaded into the embedded format appear to be suffering a drop in quality that I didn't notice before

Did we change this the other week?

**Comment by mgax** [comment]
We need to use some web magic for the images: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by mgax** [comment]
For now I've made the images load in a larger size. This might hurt page load performance, but it was not great to begin with, so we can worry about it after launch.
