### ISSUE TITLE
Setup testing

### ISSUE THREAD

**Issue by nightsh** [CRJI/theblacksea.eu#14]
We currently have no tests / no testing pipeline or tooling. This removes the need for having a Travis / CI setup now, which is pretty pointless for the time being.

The task is to 

- [ ] set up a test runner (tox?) and the necessary requirements
- [ ] write a simple test to prove the setup works as expected
- [ ] write  a `.travis.yml` file to have Travis run the tests automatically on push

**Comment by mgax** [comment]
We'll come back to it when we feel like testing.
