### ISSUE TITLE
Closing saved drafts

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#149]
When a person updates an existing story and creates a draft to be reviewed, it is not obvious how to dismiss the draft

**Comment by mgax** [comment]
There is no way to delete the draft version, but you can go to "revisions", then click on "review this revision" (for the currently published version) and then re-publish that.

![revisions](https://user-images.githubusercontent.com/27617/47618161-6bbade80-dad8-11e8-8385-e8f9c393fa50.jpg)
