### ISSUE TITLE
Update the redirects spreadsheet

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#150]
* [x] add rows to the spreadsheet (Michael / Craig)
* [x] import the spreadsheet into blacktail (Alex)

https://docs.google.com/spreadsheets/d/15gdqrCBUBz1343pZf8lvczEeDkTDutTThyTDLaEkrCI/edit?usp=drive_web&ouid=109736729480772103941

**Comment by MichaelEIC** [comment]
Do you want me to add the latest stories here?

**Comment by MichaelEIC** [comment]
OK, done. Also - can you create a new URL for the Drumul Taberei story, as
I will add this, but it will be a placeholder, as later on, after the
launch, we will need to create a bespoke page as it was before.

**Comment by MichaelEIC** [comment]
@Alex Morega <alex@grep.ro> so I should create a child page story for the
drumul taberei story, and ass the url to the spreadsheet?

**Comment by MichaelEIC** [comment]
*add not *ass

**Comment by mgax** [comment]
> so I should create a child page story for the drumul taberei story, and ass the url to the spreadsheet?

Yep. That story and the others that are missing on wagtail.
