### ISSUE TITLE
Authors not indexed

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#152]

**Comment by cpshaw99** [comment]
Authors not including in the search index

**Comment by nightsh** [comment]
Shouldn't the search be an article search, or should it be a "global search", looking everywhere? In this case, there should be some difference in search results template between, say, authors and stories, right?

**Comment by mgax** [comment]
Duplicate of https://github.com/CRJI/theblacksea.eu/issues/166
