### ISSUE TITLE
The narcisism protocol

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#166]
Currently, the indexer doesn't crawl authors in certain templates. Meaning that they don't appear in the search results.

**Comment by nightsh** [comment]
Can you provide an example?

**Comment by mgax** [comment]
https://github.com/CRJI/theblacksea.eu/blob/7c2559307cd84d4e86674d0758bb5d9a4d430381/blacktail/models/stories.py#L223-L227 <- the author is not getting indexed.
