### ISSUE TITLE
Create database seed

### ISSUE THREAD

**Issue by nightsh** [CRJI/theblacksea.eu#17]
We need a seed to prepopulate the TBS database with:

* pages structure
* story types

**Comment by mgax** [comment]
I think we can use the sqlite database that you sent me and that's currently on http://wagtail.theblacksea.eu. We can add missing things to it, and clean up before launch, which feels easier than starting with a fresh database once we feel "ready". What do you think @nightsh?

**Comment by mgax** [comment]
Yes, but do we really need postgres?

**Comment by nightsh** [comment]
As far as I'm concerned, we can also use sqlite or flat files. It's the ORM we're "fighting" here, not the engine :)

That's a good question though, do we really need any kind of dedicated DB server? If we do a good job caching the pages (\*cough\*cloudflare\*cough\*) we can keep the database interactions to a minimum. My guesstimate is that it should survive just fine on sqlite for a while.

The only problem I have with sqlite is fragmentation on disk as the db file gets larger. We might need to `VACUUM` it every once in a while. Then again, it's gonna be a small file, so let's not worry too much about performance on a 20 MiB database :)

**Comment by nightsh** [comment]
Fixed, closing.
