### ISSUE TITLE
Missing blogs

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#175]
The last 10 blog pages are missing: https://docs.google.com/spreadsheets/d/15gdqrCBUBz1343pZf8lvczEeDkTDutTThyTDLaEkrCI/edit#gid=50424262. Luckily for us, the mirror of the old website saved those same blogs here: https://theblacksea.eu/_old/mirror/theblacksea.eu/index10d0.html?idT=86&idC=86. They need to be added manually to wagtail.

**Comment by MichaelEIC** [comment]
Hi Alex

- These are added except the tenth one which doesn't appear on the mirror site
- I am not sure what the ID numbers are
- Also I hope that the old URLs and the new ones cohere, as I couldn't check the old URLs

**Comment by mgax** [comment]
> Also I hope that the old URLs and the new ones cohere, as I couldn't check the old URLs

Good thing you pointed this out. I've checked, a few of them didn't match, and I've fixed them.

> These are added except the tenth one which doesn't appear on the mirror site

Found it: https://theblacksea.eu/_old/mirror/theblacksea.eu/indexd1c8.html?idT=86&idC=96&idRec=1342&recType=story (it corrresponds to `https://theblacksea.eu/index.php?idT=86&idC=96&idRec=1342&recType=story` in the spreadsheet) - ~@MichaelEIC can you please add this one too?~ it's already in there, https://theblacksea.eu/blogs/what-makes-turkish-government-jail-journalist-read-article/

> I am not sure what the ID numbers are

It doesn't matter, I've remove the column entirely.
