### ISSUE TITLE
Homepage on Mobile

### ISSUE THREAD

**Issue by MichaelEIC** [CRJI/theblacksea.eu#179]
To start with the stories, not the blogs on the homepage on mobile

**Comment by cpshaw99** [comment]
We are going to do a redesign of the grey part of the homepage. So this will end up being redundant

**Comment by cpshaw99** [comment]
I am talking from my ass.

**Comment by mgax** [comment]
I'm adopting the easy solution: hide the blogs on mobile. Also the headline image since it looks weird above the first story's image.
