### ISSUE TITLE
Migrate "yaml" articles

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#24]
The "yaml" articles, like https://theblacksea.eu/stories/article/en/living-on-the-edge-photostory, need to be mograted to the wagtail database.

**Comment by nightsh** [comment]
There are two approaches I imagined for this:

1. Scrape them, as the format / template and selectors are the same in all articles.

2. Expand on the [tbs-importer](https://github.com/nightsh/tbs-importer) repository to be able to import yaml files. This would have issues with a) images paths and b) URLs for the articles.

Personally, I'd use the tbs-importer scripts to be able to use the scraped html content as a data source.

Does it make sense?

**Comment by mgax** [comment]
Yeah, whichever is easiest. Don't worry too much about image URLs as we can easily replace them.

**Comment by mgax** [comment]
Done? If so, close please.

**Comment by mgax** [comment]
@mrc-toader points out that we'll have new yaml articles by the time we launch the wagtail version. Keep the script handy, we'll need it again :)

**Comment by nightsh** [comment]
If there are just a handful of them, we might even copy and paste them, not sure it's worth an extra fixture for a few more pieces.

**Comment by mgax** [comment]
Also covered by #70
