### ISSUE TITLE
Re-host old images

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#26]
Migrated articles (http://wagtail.theblacksea.eu/stories/azeri-ruling-dynasty-offshore-links-potentially-in-violation-of-law/) contain links to images like this one: `http://theblacksea.eu/RES/uploads/images/Baku_Flame_Towers(1).jpg`. We need to copy all of them to the new CMS and update the links to use HTTPS. Actually, they should be relative to the site root (e.g. `/RES/uploads/images/Baku_Flame_Towers(1).jpg`), so the http/https happens automagically.

**Comment by nightsh** [comment]
We don't need to update the links, if we're doing a HTTP -> HTTPS redirect. BUT – browsers would likely warn about mixed content in a HTTPS page, so one approach would probably be a SQL `REPLACE` query ran on all article contents.
