### ISSUE TITLE
Migrate article hero images

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#27]
Currently, migrated articles, e.g. http://wagtail.theblacksea.eu/stories/azeri-ruling-dynasty-offshore-links-potentially-in-violation-of-law/, have no "hero" images (the headline image that serves as background to the title).

**Comment by mgax** [comment]
@nightsh, you said you'd get somebody to migrate them, IIRC?

**Comment by nightsh** [comment]
Yup, that could be done manually, as it's a one time operation. It'd be rather costly to automate, I guess :)
The somebody I talked with to help with this is waiting for a green light and some instructions, maybe a screen sharing session to demonstrate how. That's all.

**Comment by mgax** [comment]
Closing in favour of https://github.com/CRJI/theblacksea.eu/issues/40
