### ISSUE TITLE
Design details - new layout

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#28]
Michael is not happy with the visual details of the reimplemented layout. We should make everything as similar as possible to the old layout - fonts, colors, box sizes, everything.

* [ ] navbar: "the black sea" is bigger than "diving deep into stories"
* [ ] navbar: "blogs", "about" and "stories" are too close together and unevenly spaced
* [ ] the search box and search button are too big with too much spacing

**Comment by nightsh** [comment]
@mrc-toader could you take a look at this?
