### ISSUE TITLE
Pull quotes

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#29]
The articles have no pull quotes, and their content is not part of the article body. We should bring them back.

**Comment by nightsh** [comment]
Same as my comment on #30, if we bring back the old template for old articles, we shall have them,

**Comment by mgax** [comment]
What about the content for the pull quotes, is it already in the migrated articles?

**Comment by nightsh** [comment]
If they're not (I don't remember), I can update the importer to add them.

**Comment by mgax** [comment]
Michael says pull quotes are unimportant, so let's forget about them.
