### ISSUE TITLE
Comments (disqus)

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#31]
The old website has disqus comments. Migrating them _should_ be as simple as setting up redirects (https://github.com/CRJI/theblacksea.eu/issues/23), enabling disqus on the wagtail website, and using their [migration tool](https://help.disqus.com/customer/en/portal/articles/286778-migration-tools) to follow the redirects and migrate the comments to the new article URLs.

**Comment by nightsh** [comment]
Have a look at #15, we might leave them behind, for good.

**Comment by mgax** [comment]
> Have a look at #15, we might leave them behind, for good.

Ah, good, then I'll just close this issue.
