### ISSUE TITLE
Migrate "blog" articles

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#32]
Import the blog posts from the old CMS.

**Comment by mgax** [comment]
Done? If so, close please.

**Comment by mgax** [comment]
Nope, blogs are not there, and the journalists want to keep them.

**Comment by nightsh** [comment]
I created a draft blog post and they showed up. It's an issue I can't get to the bottom of, but something is wrong with the imported items structure.

**Comment by mgax** [comment]
You're right, I see them now. Ok. Closing this issue; will open new ones if needed.
