### ISSUE TITLE
Authors pages

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#35]
https://github.com/theblacksea/issues/issues/5

**Comment by cpshaw99** [comment]
- Cannot access or edit individual author pages.
- Ad blocker kills some photos on authors page (this is still an issue?)

**Comment by mgax** [comment]
It's kind of a hack, but you can edit author bios and other information from here: https://wagtail.theblacksea.eu/admin/blacktail/author/. The author pages are not actual pages (like stories and blogs).
