### ISSUE TITLE
Script to fix HTML escape codes in titles

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#39]
http://wagtail.theblacksea.eu/stories/lets-talk-about-sex-in-moldova/

**Comment by nightsh** [comment]
If you do a script that goes through all articles running some arbitrary cleanup ops, maybe we can find some other things we can tell it to do. And re-run it every time we find something else to script-clean. Right?

**Comment by mgax** [comment]
Yes, for sure. I'll save it somewhere in the repo.

**Comment by mgax** [comment]
Fixed in https://github.com/CRJI/theblacksea.eu/commit/1ec9197c8ee269a066f558e15e747b3ee0eaaad8. An earlier iteration of the script added two drafts to each article, whoops :D
