### ISSUE TITLE
Change homepage image on old website

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#41]

**Comment by nightsh** [comment]
Done.

**Comment by MichaelEIC** [comment]
Great, the thumb also needs to change, as it shows the old version - it might just be a case of refresh somewhere

**Comment by nightsh** [comment]
@MichaelEIC if that's the facebook sharing thumbnail, then I told fb to rescrape it now and purged the cache, tested, should be fine. Closing again.
