### ISSUE TITLE
Server monitoring

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#48]
Set up monit to watch `theblacksea.eu`, `m.theblacksea.eu` and `wagtail.theblacksea.eu`, so we get notified about downtime.

**Comment by mgax** [comment]
Done, monit is set up, @nightsh @mrc-toader @cpshaw99 @germakoci @MichaelEIC let me know if you want to get notified when the website goes down.

**Comment by germakoci** [comment]
sure, thanks !

**Comment by MichaelEIC** [comment]
Yes, will do

**Comment by mgax** [comment]
@germakoci @MichaelEIC I just killed wagtail for a minute to test alerts, did you get emails?

**Comment by MichaelEIC** [comment]
Yes thanks
