### ISSUE TITLE
Create a mapping between old and new URLs

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#51]
In order to redirect old URLs to new URLs, and make sure we don't miss any content in the migration, we need a complete mapping between the old and new articles.

* spreadsheet with mapping: https://docs.google.com/spreadsheets/d/15gdqrCBUBz1343pZf8lvczEeDkTDutTThyTDLaEkrCI/edit#gid=1590954652
* raw data: https://gist.github.com/mgax/65295573844f6daaf611e38989937397

**Comment by mgax** [comment]
I've matched all the articles I could match automatically, and did a few by hand (sheet 1), but there are 28 articles in the new site that are still unmapped (sheet 2). Somebody should go through sheet 2 and move those rows to sheet 1 where they belong.

**Comment by mgax** [comment]
Some stories got moved to story folders: https://wagtail.theblacksea.eu/stories/malta-files/cash-loans-czar-s-maltese-tax-escape-plan/ and https://wagtail.theblacksea.eu/stories/malta-files/maltese-law-firm-confirms-erdogan-company-offshore-bank-account/

**Comment by nightsh** [comment]
Blocked by #70

**Comment by mgax** [comment]
@MichaelEIC @cpshaw99 I've collated all the story URLs in a single spreadsheet. A few are missing; please check them and correct them. The list is copied to the website's source code, let me know when you make changes so I can update it.

The website will now redirect like so:

* [/index.php?idT=88&idC=88&idRec=1284&recType=story](https://wagtail.theblacksea.eu/index.php?idT=88&idC=88&idRec=1284&recType=story) -> [/stories/football-leaks/tu-rkiyedeki-gizli-ortakliklar-rus-mafyasi-ve-bir-devlet-baskani-2-bo-lu-m/](https://wagtail.theblacksea.eu/stories/football-leaks/tu-rkiyedeki-gizli-ortakliklar-rus-mafyasi-ve-bir-devlet-baskani-2-bo-lu-m/)
* [/tabloids-vs-romania](https://wagtail.theblacksea.eu/tabloids-vs-romania) -> [/stories/what-happened-after-the-sun-left-town/](https://wagtail.theblacksea.eu/stories/what-happened-after-the-sun-left-town/)

**Comment by mgax** [comment]
https://docs.google.com/spreadsheets/d/15gdqrCBUBz1343pZf8lvczEeDkTDutTThyTDLaEkrCI/edit#gid=1480092930

**Comment by mgax** [comment]
Blog URLs mapped too, in the same spreadsheet.
