### ISSUE TITLE
Homepage articles are out-of-order or some are missing

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#68]

**Comment by nightsh** [comment]
Order was fixed, the missing articles will be fixed by #70 and they are tracked in #51.

**Comment by mgax** [comment]
But no, the order is still not right. The first article is [Football Leaks: Mesut Özil in Spanish tax authority probe](https://wagtail.theblacksea.eu/stories/football-leaks/football-leaks-mesut-o-zil-in-spanish-tax-authority-probe/) from 2016-12-02, when there is [Living on the Edge](https://wagtail.theblacksea.eu/stories/living-on-the-edge/) from 2018-02-05 which doesn't show up.
