### ISSUE TITLE
Management command to import article

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#70]
The command should accept an argument which is the URL of an article on the old website. It should fetch the article and import it into the wagtail database.

**Comment by nightsh** [comment]
Done, but it complains about duplicating existing slugs. Debugging now, might be an unrelated database integrity issue, maybe garbage from old scraping attempts , or maybe it's still related to the command code. 

For the record, I'll paste here the validation error django throws at me:

```
{'slug': ['This slug is already in use']}
```

**Comment by nightsh** [comment]
Some pages are still missing, they will be added as soon as we have multiple templates implemented in the platform, as their layout is somehow "special" and could not be scraped accurately with the existing import tools.

- https://theblacksea.eu/syrian-refugees-child-labour/
- https://theblacksea.eu/eurocrimes/
- https://theblacksea.eu/donbass

All the others are now in and the url mapping is up to date.
