### ISSUE TITLE
Photo gallery

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#72]
Streamfield item for a photo gallery powered by https://galleria.io/

**Comment by mrc-toader** [comment]
I'm suggesting Bootstrap4's carousel (with controls and captions), since we (probably) already have it installed, also looks modern and is responsive/mobile-friendly:
`https://getbootstrap.com/docs/4.0/components/carousel/#with-captions`

**Comment by mgax** [comment]
> I'm suggesting Bootstrap4's carousel

I like the back/forward links better in the Bootstrap carousel, the clickable area is much larger.

**Comment by germakoci** [comment]
maybe you want to have a look here: https://github.com/guardian/grid 
the guardian is using this for production and they released the code; if it scales with them it's good for any media ops [explainer/demo here http://www.niemanlab.org/2015/08/the-guardian-debuts-grid-an-open-source-image-management-system/ ]
