### ISSUE TITLE
Headlines, spacing and font size

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#87]
Relates to the stories feed or homepage. The spacing between the headline is off.

**Comment by nightsh** [comment]
As in, too big between rows in a headline?

**Comment by cpshaw99** [comment]
The space is too wide, like it's a new papagrah, 

![headlines](https://user-images.githubusercontent.com/29917101/46365279-d404d480-c680-11e8-8ec2-86ee4627bcee.png)

**Comment by mgax** [comment]
Fixed.
