### ISSUE TITLE
DESIGN DAY

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#90]
Blacktail template needs some adjustments, to make text smaller etc 
* [x] home page
* [x] search results page
* [x] author page
* [x] story template - blacktail
* [x] story template - malta
* [x] story template - legacy
* [x] stories page
* [x] story folder page
* [x] about page
* [x] blogs page
* [x] individual blog page

**Comment by nightsh** [comment]
Please post a list of the things to be altered on the template. Here is fine, for everyone to see and follow progress.

**Comment by germakoci** [comment]
you need a checkbox list instead of etc, something like:

- [ ] etc 
- [ ] etc 
- [ ] etc

**Comment by mgax** [comment]
Done, good enough for launch.
