### ISSUE TITLE
Bylines

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#93]
Two issues here:

1. We can only add a byline if the author has a log in/account
2. The authors are ordered 'randomly'

... should correct these

**Comment by nightsh** [comment]
This does not apply to this project. In the Wagtail-powered platform this limitation was removed. This is only an issue in the legacy platform.

Regarding the order, I don't see the issue there. The randomization was a feature to avoid prioritization by hand of some authors over others. It's extremely easy to remove, please create a separate issue if you want that.
