### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by MichaelEIC** [CRJI/theblacksea.eu#96]
The social media icons do not appear on the old template

A version with wagtail:
https://wagtail.theblacksea.eu/admin/pages/1095/edit/preview/

![screen shot 2018-09-28 at 13 40 59](https://user-images.githubusercontent.com/30523098/46204016-59585400-c324-11e8-98dc-7193717dc2da.png)

Here is a version without wagtail:
https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1223&recType=story

![screen shot 2018-09-28 at 13 42 54](https://user-images.githubusercontent.com/30523098/46204044-77be4f80-c324-11e8-93ad-50425baf7169.png)

On the Malta template, the Twitter icon does not appear:

https://wagtail.theblacksea.eu/admin/pages/1123/edit/preview/

![screen shot 2018-09-28 at 13 43 50](https://user-images.githubusercontent.com/30523098/46204078-93295a80-c324-11e8-9b1c-bfa0f323fcf1.png)

**Comment by germakoci** [comment]
@MichaelEIC please stop posting admin urls ! please upload screenshots instead. thanks

**Comment by mgax** [comment]
> please stop posting admin urls

That's ok, they are behind a login, and the code is open source anyway.
